### ISSUE TITLE
User installed assyst

### ISSUE THREAD

**Issue by DemonTamer534** [Jacherr/assyst2#22]
**What would you like to see added to Assyst?**
Since assyst already has slash commands i think it would be pretty cool to add those as user installed commands as well

**Additional context**
Below is a carefully crafted recreation of what that would look like in practice 

![2F023BDB-C864-4C09-BE48-CC2632B31A80](https://github.com/user-attachments/assets/24142108-d7e4-46c0-ae69-90f6146aef30)

**Comment by Jacherr** [comment]
Library support is missing for now, but can tackle this when it's added. Will also need to refactor some commands not available in DMs or private channels to make sure that they also respect these conditions with user installed apps.

**Comment by Jacherr** [comment]
Prelim version of this should be working now.
