### ISSUE TITLE
Cannot use spoilers in tags

### ISSUE THREAD

**Issue by Tolga1452** [Jacherr/assyst2#25]
**Describe the bug**
You are not able to use spoilers as a content in tags.

**To Reproduce**
1. Create a tag with a content that contains a ||spoiler||.
2. Use the tag.

**Expected behavior**
Tag output should contain the spoiler.

**Screenshots**
![image](https://github.com/user-attachments/assets/497f7458-be99-4cf1-9de2-5630379b1979)
![image](https://github.com/user-attachments/assets/545542c6-c8bf-4a21-a7af-6329d28ff554)

**Comment by meqativ** [comment]
as a workaround you can escape the | with \
![image](https://github.com/user-attachments/assets/c4597aa3-e8a2-435c-8012-cbfa0b15e1a6)
(i think it interprets it as an argument separator <kbd>{name:arg|arg|arg|arg}</kbd>)
